language: java
install: "./gradlew assemble"
script:
- "./gradlew test"
- "./gradlew build"
- "./gradlew run"
notifications:
  slack:
    rooms:
    - secure: FkTuFpZ9mG7MYtRQBDCy9mqQSQx6CYK+603E+w37WejqAZ1t46a7yB/S+vJd/Su0RqJJhNhAUTXIKg8rnzdxNHbNmlePFauHkTYGorNbaBerjjXt2RBJZRj5fpbmlYeMupqvXuN46qAF/bPKz6DI+HKdgVGkcJqTG2jQ++e7pmMk9iv33cm0xftj7CvOgmwlpXqIGeMm4DJPBNDwheGNWQgmqyUuo/NfqNH5vtDzmvAzbxV3WP46wgn3RuGqOujJrSaigH/wJcpM9nuQ2Xg+LgVw73/rvc2D6NHcehM4ML1jrFfeYfj6O/nBMF8yugeKC1uw9gfyyjgUIs6d9paKpGg3PpWK+NEaP/twSjp0QfxLjDU1k4vfK3THXT/vChJyReA1Kob1HYcvlUkv7uL6U5MeOcVfKb1erUZXWXus/QgFSMr0QF1dkUfauGYp89txKlf17cJhlQIBVeXMTSc+7f9taxfLXgNvnG0SNNbTZEHUOEYROTSVYSSioODF5hTPTdOP1Pt1UzmlerTYyrLa0JOgNwyq/2VO4Pql9iELg+Qqh0ZFcsSbehAA8wCpuAzvqaSPr5fKIjhYgSMR1yTZz1G2/KfTe0iViRCa+H5wezxgeLmNE/bIyDCKYGQBiwDPVfIpqirJFJD9uPJoyQjdhMdpZhqU4e4R1Dhxdga0oI8=
    on_success: always
    on_failure: always
env:
  global:
    secure: CIobVfy3cS1xeVIDUIxA65T8Bgd6k0s8c223pSX8KU2zzylArj0tc1k+INs7dHgGaOcKtzfGK2BHkx7AXuourfozG3v+lM+xZECJX/oHhoHtmGe2OGJPqN1sg5Ve7woTCAE7hNGYsX6uEN1mWrZO56IARmEXmezVm7YtYel8NxbQHA4WhpQZMiiUg6LzlBbRiPRb1WCrVEWyJWE7hnQnrKcFlBLTTuwx4cldqpUBmWtbe7kZayCsLIAhNhqf93QnJZ3K+0KJDa2eapdetOYQ69sSPliPRmyzEksnzD1/V9Y2+mUTqwAqgLdwYYC+D6bBfDLUEjiLenIXzM+WRhGei+vq1ua9xJY0HouU4yHcOv3DSk9mVTGRP+gWK1LwJEaHqbXNEf15W5pjZS39ffNLkmN1ixkvPiiZvES6Bt5MJsq6TyyYSMEtYEaixwr2fpWFgw19QlpcXMWVjTwxQstiljp2WaFf6Lm6YT30z3xrArnPAY+MrGGrlwQuC77MQLBQv95EcKdl4y0NCVQOOQPK/FJJJ5IgBmKEceRhatOUrMFXWK9gK2ZpEKzGxO7s4DQx9HBY3oevPv+FQVZ5UYfjEYWN8onRvlahX8QZj4+aKfMVnpG4yGyJ53n0Yu+9hoRPxNSFcsvrAdFwcRGsPbOBQyQSkCuHhrbzMax+Zh6T0jg=
deploy:
  api_key:
    secure: HBLq5GkY8Z3BQI/6lumJkLfcaTfl26GJ5M+ESS6vwLUeNUoHfgYbkziCwvB9X0QrRWoHo9lh9ATekjnFRjJDkqnv0Hl7wyjIC06FxEYjbPu073Ku3Ss3hsa37wATTuzkk/3TOCYN3mlmjkBpiegsVfoVy4m6RWzec8R+ic9+C9k+EGYpzsiy28dREkH2DFzae0eydMSpnG69VLZ23xD69p0bEUJ/fuQA/UnY9y5LL4DRa9MSLdIyUgm2QMxnOV65LITbrS1HSvNadLxVExO+sQPFDd+Zgzs6qt9xksJX/qHKxKmIhJocuCBjjrivywK/ALeVTZSGhZJIoO7SjyV+GgWUgfMYtwTF8JooyXnx3/Nvn5fbvXrXaLU4xpot9S1Pyn9j01933TdtJEQm6XpfRrJfZp4z5FFydeh8YrIZYiRrsMioHMwK55n7XezSyL9NuqmL7KpEIAyqf5oYuT2zQXYoGJSQLQ4uXnuVWBqv7+zb13WpucOmaXdf3VviwIhwYJXLREXni30LXTlkzkG0BASF8Bf8l0rmzGJSSB++cpNHwKZIDsWkZFbEK2pfFsDQmbQa4vwU/zcN3bLS+UeRQF4UhOWHfQqqYZARuFkQOftwj4+D6n4qduUcFg/4px5hbwvC+JXn1kwnPUpm2CrBiwJHgj1SwtHOlAgvhcs7yjI=
  app: praxis-homework-four
  run: "./gradlew run"